routes/web.php
<?php

use Illuminate\Support\Facades\Route;


Route::get('/', function () {
    return view('welcome');
});

Auth::routes();
Route::group(['middleware' => ['web', 'auth', 'admin'],'prefix' => 'admin'], function () {
    Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');
    Route::resource('companies', App\Http\Controllers\CompaniesController::class);
    Route::resource('categories', App\Http\Controllers\CategoriesController::class);
    Route::get('categories/{id}/delete', [App\Http\Controllers\CategoriesController::class, 'destroy']);
    Route::resource('products', App\Http\Controllers\ProductsController::class);
    Route::resource('settings', App\Http\Controllers\SettingsController::class);
});
Route::get('permissions', [App\Http\Controllers\HomeController::class, 'permissions'])->name('permissions');

app/Http/Controllers/CategoriesController.php
<?php

namespace App\Http\Controllers;

use App\Models\Categories;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Session;

class CategoriesController extends Controller
{

    public function index()
    {
        $categories = Categories::getTree();
        $data = ['categories' => $categories];
        return view('categories.index')->with($data);
    }

    public function create()
    {
        $categories = Categories::getList();
        $data = ['categories' => $categories];
        return view('categories.create')->with($data);
    }

    public function store(Request $request)
    {
        $name = $request->get('name');
        $parent_id = $request->get('parent_id');


        if (!isset($parent_id)) {
            $data = ['name' => $name];

            Categories::create($data);

            Session::flash('flash_message', 'Category successfully added!');
            return redirect()->back();
        }
        $category = Categories::FindOrFail($parent_id);
        Categories::create(['name' => $name], $category);
        Session::flash('flash_message', 'Category successfully added!');
        return redirect()->back();
    }

    public function show($id)
    {
        //
    }

    public function edit($id)
    {
        $category = Categories::FindOrFail($id);
        $categories = Categories::getList();
        $data = ['category' => $category, 'categories' => $categories];
        return view('categories.edit')->with($data);
    }

    public function update(Request $request, $id)
    {
        $category = Categories::FindOrFail($id);
        $input = $request->all();
        $category->fill($input)->save();
        Session::flash('flash_message', 'Category successfully edited.');

        $categories = Categories::getTree();
        $data = ['categories' => $categories];
        return view('categories.index')->with($data);
    }

    public function destroy($id)
    { $category = Categories::FindOrFail($id);
        $category->delete();
        $categories = Categories::all();
        $data = ['categories' => $categories];
        return redirect('/admin/categories')->with($data);

    }
}

resources/views/categories/create.blade.php
@extends('layouts.dashboard')

@section('content')

    <div class="container">
        <div class="row">

            @if(Session::has('flash_message'))
                <div class="alert alert-success">
                    {{ Session::get('flash_message') }}
                </div>
            @endif


            <div class="col-12">
                <form action="{{ route('categories.store') }}" method="POST" enctype="multipart/form-data">
                    @csrf


                    <div class="form-group row">
                        <label for="name" class="col-md-4 col-form-label text-md-right">Category Name</label>
                        <div class="col-md-6">
                            <input id="name" type="text" class="form-control" name="name" autocomplete="name" required>
                        </div>
                    </div>

                    <div class="form-group row">
                        <label for="parent_id" class="col-md-4 col-form-label text-md-right">Subcategory</label>
                        <div class="col-md-6">
                            <select class="form-control @error('parent_id') is-invalid @enderror" name="parent_id"
                            >
                                <option value="">Main Category</option>
                                {!! $categories !!}
                            </select>
                            @error('parent_id')
                            <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                            @enderror
                        </div>
                    </div>


                    <div class="form-group row">
                        <div class="col-md-6">
                            <button type="submit" class="btn btn-primary">Add</button>
                        </div>
                    </div>

                </form>
            </div>
        </div>
    </div>

@endsection

resources/views/categories/edit.blade.php
@extends('layouts.dashboard')

@section('content')

    <div class="container">
        <div class="row">
            <div class="col-12">
                <form action="{{ route('categories.update', $category) }}" method="POST">
                    @method('PUT')
                    @csrf

                    <div class="form-group row">
                        <label for="name" class="col-md-4 col-form-label text-md-right">Category Name</label>
                        <div class="col-md-6">
                            <input id="name" type="text" class="form-control" name="name" value="{{ $category->name }}" autocomplete="name" required>
                        </div>
                    </div>

                    <div class="form-group row">
                        <label for="parent_id" class="col-md-4 col-form-label text-md-right">Subcategory</label>
                        <div class="col-md-6">
                            <select class="form-control @error('parent_id') is-invalid @enderror" name="parent_id"
                            >
                                <option value="">Main Category</option>
                                {!! $categories !!}
                            </select>
                            @error('parent_id')
                            <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                            @enderror
                        </div>
                    </div>

                    <div class="form-group row">

                        <div class="col-md-6">
                            <button type="submit" class="btn btn-info">Save</button>
                        </div>
                    </div>

                </form>
            </div>
        </div>
    </div>
    <form action="{{ route('categories.destroy', $category) }}" method="POST">
        @csrf
        @method('DELETE')
        <button type="submit" class="btn btn-danger">Delete</button>
    </form>

@endsection

@section('scripts')
    <script>
        $('[name=parent_id]').val({{ $category->parent_id }});
    </script>
@endsection

resources/views/categories/index.blade.php
@extends('layouts.dashboard')

@section('content')

    <div class="container">
        <div class="row">
            <div class="col-8">
                <a href="{{ route('categories.create') }}" class="btn btn-primary">Add Category</a>
            </div>
        </div>
        {!! $categories  !!}
    </div>
@endsection