routes/web.php
<?php

use Illuminate\Support\Facades\Route;


Route::get('/', function () {
    return view('welcome');
});

Auth::routes();
Route::group(['middleware' => ['web', 'auth', 'admin'],'prefix' => 'admin'], function () {
    Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');
    Route::resource('companies', App\Http\Controllers\CompaniesController::class);
    Route::resource('categories', App\Http\Controllers\CategoriesController::class);
    Route::get('categories/{id}/delete', [App\Http\Controllers\CategoriesController::class, 'destroy']);
    Route::resource('products', App\Http\Controllers\ProductsController::class);
    Route::resource('settings', App\Http\Controllers\SettingsController::class);
});
Route::get('permissions', [App\Http\Controllers\HomeController::class, 'permissions'])->name('permissions');

app/Models/Products.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Products extends Model
{
    protected $fillable = [
        'name',
        'quantity',
        'price',
        'image',
        'country_id',
        'cat_id'
    ];

    public function categories()
    {
        return $this->belongsTo(Categories::class);
    }

    public function countries()
    {
        return $this->belongsTo(Countries::class, 'country_id');
    }
}

app/Http/Controllers/ProductsController.php
<?php

namespace App\Http\Controllers;

use App\Http\Helper\ImageStore;
use App\Models\Categories;
use App\Models\Countries;
use App\Models\Products;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Session;
use Illuminate\Support\Facades\Validator;


class ProductsController extends Controller
{

    public function index()
    {
        $products = Products::all();
        $data = ['products' => $products];
        return view('products.index')->with($data);
    }

    public function create()
    {
        $categories = Categories::getList();
        $countries = Countries::all();
        $data = ['countries' => $countries, 'categories' => $categories];
        return view('products.create')->with($data);
    }

    public function store(Request $request)
    {
        $validator = Validator::make($request->all(), [
            'name' => ['required', 'string', 'max:255'],
            'quantity'  => ['required', 'integer',],
            'price'      => ['required', 'integer'],
            'image'   => ['required', 'image'],
            'cat_id'       => ['required', 'integer'],
            'country_id'       => ['required', 'integer']
        ]);

        if ($validator->fails()) {
            return redirect('admin/products/create')
                ->withErrors($validator)
                ->withInput();
        }
        $imageObj = new ImageStore($request, 'products');
        $image = $imageObj->imageStore();

        Products::create([
            'name' => $request->get('name'),
            'quantity'  => $request->get('quantity'),
            'price'      => $request->get('price'),
            'image'      => $image,
            'cat_id'    => $request->get('cat_id'),
            'country_id'    => $request->get('country_id')

        ]);

        Session::flash('flash_message', 'Product successfully created!');
        $products = Products::all();
        $data = ['products' => $products];
        return redirect('/admin/products')->with($data);
    }

    public function show($id)
    {
        $product = Products::FindOrFail($id);
        $country = Countries::all();
        $category = Categories::all();
        $data = ["product" => $product, "country" => $country, "category" => $category];
        return view('products.show')->with($data);
    }

    public function edit($id)
    {
        $product = Products::FindOrFail($id);
        $country = Countries::all();
        $category = Categories::all();
        $data = ["product" => $product, "country" => $country, "category" => $category];
        return view('users.edit')->with($data);
    }

    public function update(Request $request, $id)
    {
        //
    }


    public function destroy($id)
    {
        //
    }
}

resources/views/products/create.blade.php
@extends('layouts.dashboard')
@section('content')
    <div class="container">
        <div class="row">
            @if(Session::has('flash_message'))
                <div class="alert alert-success">
                    {{ Session::get('flash_message') }}
                </div>
            @endif
            <div class="col-12">
                <form action="{{ route('products.store') }}" method="POST" enctype="multipart/form-data">
                    @csrf
                    <div class="form-group row">
                        <div class="col-md-6">
                            <label class="btn btn-default">
                                Upload Image <input type="file" class="form-control @error('image') is-invalid @enderror" id="image" name="image" hidden>
                            </label>
                            @error('image')
                            <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                            @enderror
                        </div>
                    </div>
                    <div class="form-group row">
                        <label for="name" class="col-md-4 col-form-label text-md-right">Name</label>
                        <div class="col-md-6">
                            <input id="name" type="text" class="form-control @error('name') is-invalid @enderror"
                                   value="{{ old('name') }}" name="name" autocomplete="name" required
                                   autofocus>
                            @error('name')
                            <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                            @enderror
                        </div>
                    </div>
                    <div class="form-group row">
                        <label for="quantity" class="col-md-4 col-form-label text-md-right">Quantity</label>
                        <div class="col-md-6">
                            <input id="quantity" type="text" class="form-control @error('quantity') is-invalid @enderror"
                                   value="{{ old('quantity') }}" name="quantity" required>
                            @error('quantity')
                            <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                            @enderror
                        </div>
                    </div>
                    <div class="form-group row">
                        <label for="price" class="col-md-4 col-form-label text-md-right">Price</label>
                        <div class="col-md-6">
                            <input id="price" type="text" class="form-control @error('price') is-invalid @enderror"
                                   name="price" value="{{ old('price') }}" required>
                            @error('price')
                            <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                            @enderror
                        </div>
                    </div>
                    <div class="form-group row">
                        <label for="cat_id" class="col-md-4 col-form-label text-md-right">Select Category</label>
                        <div class="col-md-6">
                            <select class="form-control  @error('cat_id') is-invalid @enderror" name="cat_id" required>
                               {!! $categories !!}
                            </select>
                            @error('cat_id')
                            <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                            @enderror
                        </div>
                    </div>
                    <div class="form-group row">
                        <label for="country_id" class="col-md-4 col-form-label text-md-right">Select Country</label>
                        <div class="col-md-6">
                            <select class="form-control @error('country_id') is-invalid @enderror" name="country_id" required>
                                @foreach($countries as $country)
                                    <option value="{{ $country->id }}">{{ $country->name }}</option>
                                @endforeach
                            </select>
                            @error('country_id')
                            <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                            @enderror
                        </div>
                    </div>
                    <div class="form-group row">
                        <div class="col-md-6">
                            <button type="submit" class="btn btn-fill btn-primary">Save</button>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
@endsection

resources/views/products/index.blade.php
@extends('layouts.dashboard')
@section('content')
    <div class="container">
        <div class="row">
            <div class="col-12">
                <table class="table table-green">
                    <thead>
                    <tr>
                        <th scope="col">ID</th>
                        <th scope="col"></th>
                        <th scope="col">Name</th>
                        <th scope="col">Quantity</th>
                        <th scope="col">Price</th>
                        <th scope="col">Country</th>
                    </tr>
                    </thead>

                    <tbody>
                    @foreach($products as $product)
                        <tr>
                            <td><a href="/admin/user/{{ $product->id }}">{{ $product->id }}</a></td>
                            <td><img class="img-wrapper" width="40px" height="40px" src="/assets/img/products/thumbnails/{{ $product->image }}"></td>
                            <td>{{$product->name}}</td>
                            <td>{{$product->quantity}}</td>
                            <td>{{$product->price}}</td>
                            <td>{{$product->countries->full_name}}</td>
                        </tr>
                    </tbody>
                    @endforeach
                </table>
                <div class="container">
                    <div class="row">
                        <div class="col-12">
                            <a class="btn btn-outline-success" href="/admin/products/create">+ Add Product</a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection