routes/web.php
<?php

use Illuminate\Support\Facades\Route;


Route::get('/', function () {
    return view('welcome');
});

Auth::routes();
Route::group(['middleware' => ['web', 'auth', 'admin'],'prefix' => 'admin'], function () {
    Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');
    Route::resource('companies', App\Http\Controllers\CompaniesController::class);
    Route::resource('categories', App\Http\Controllers\CategoriesController::class);
    Route::get('categories/{id}/delete', [App\Http\Controllers\CategoriesController::class, 'destroy']);
    Route::resource('products', App\Http\Controllers\ProductsController::class);
    Route::resource('settings', App\Http\Controllers\SettingsController::class);
});
Route::get('permissions', [App\Http\Controllers\HomeController::class, 'permissions'])->name('permissions');

app/Models/Settings.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Settings extends Model
{
    use HasFactory;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */

    protected $fillable = [
        'url',
        'email',
        'title',
        'facebook',
        'instagram',
        'twitter',
        'linked_in',
        'phone',
        'description',
        'logo'
    ];
}

app/Http/Controllers/SettingsController.php
<?php

namespace App\Http\Controllers;

use App\Models\Settings;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Session;
use Illuminate\Support\Facades\Validator;
use App\Http\Helper\ImageStore;

class SettingsController extends Controller
{
    public function index()
    {
        $settings = Settings::all();
        $data = ['settings' => $settings];
        return view('settings.index')->with($data);
    }

    public function create()
    {
        return view('settings.create');
    }

    public function store(Request $request)
    {
        $validator = Validator::make($request->all(), [
            'url' => ['required', 'string', 'max:255'],
            'facebook' => ['required', 'string', 'max:255'],
            'email' => ['required', 'string', 'email', 'max:255'],
            'linked_in' => ['required', 'string', 'min:8'],
            'twitter' => ['required', 'string', 'min:8'],
            'instagram' => ['required', 'string', 'min:8'],
            'description' => ['required', 'string', 'min:8'],
            'phone' => ['required', 'string', 'min:8'],
            'image' => ['required', 'image'],
            'title' => ['required', 'string', 'min:8']
        ]);

        if ($validator->fails()) {

            return redirect('admin/settings/create')
                ->withErrors($validator)
                ->withInput();
        }

        $imageObj = new ImageStore($request, 'settings');
        $image = $imageObj->imageStore();

        Settings::create([
            'url' => $request->get('url'),
            'facebook' => $request->get('facebook'),
            'instagram' => $request->get('instagram'),
            'email' => $request->get('email'),
            'logo' => $image,
            'twitter' => $request->get('twitter'),
            'linked_in' => $request->get('linked_in'),
            'description' => $request->get('description'),
            'phone' => $request->get('phone'),
            'title' => $request->get('title')
        ]);

        Session::flash('flash_message', 'Settings successfully created!');
        return redirect()->back();
    }

    public function show($id)
    {
        //TODO
    }
    public function edit($id)
    {
        //TODO
    }
    public function update(Request $request, $id)
    {
        //TODO
    }

    public function destroy($id)
    {
        //TODO
    }
}

resources/views/settings/create.blade.php
@extends('layouts.dashboard')


@section('content')
    <div class="container">
        <div class="row">

            @if(Session::has('flash_message'))
                <div class="alert alert-success">
                    {{ Session::get('flash_message') }}
                </div>
            @endif

            <div class="col-12">
                <form action="{{ route('settings.store') }}" method="POST" enctype="multipart/form-data">
                    @csrf

                    <div class="form-group row">
                        <div class="form-group row">
                            <div class="col-md-6">
                                <label class="btn btn-default">
                                    Upload Logo <input type="file" id="image" name="image" hidden>
                                </label>
                            </div>
                        </div>
                    </div>

                    <div class="form-group row">
                        <label for="url" class="col-md-4 col-form-label text-md-right">URL</label>
                        <div class="col-md-6">
                            <input id="url" type="text" class="form-control @error('url') is-invalid @enderror" value="{{ old('url') }}" name="url" autocomplete="url" required autofocus>
                            @error('url')
                            <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                            @enderror

                        </div>
                    </div>



                    <div class="form-group row">
                        <label for="title" class="col-md-4 col-form-label text-md-right">Title</label>
                        <div class="col-md-6">
                            <input id="title" type="text" class="form-control @error('title') is-invalid @enderror" value="{{ old('title') }}" name="title" required >
                            @error('title')
                            <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                            @enderror
                        </div>
                    </div>

                    <div class="form-group row">
                        <label for="name" class="col-md-4 col-form-label text-md-right">Email</label>
                        <div class="col-md-6">
                            <input id="name" type="email" class="form-control @error('email') is-invalid @enderror" name="email" value="{{ old('email') }}"  required>
                            @error('email')
                            <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                            @enderror
                        </div>
                    </div>


                    <div class="form-group row">
                        <label for="facebook" class="col-md-4 col-form-label text-md-right">Facebook</label>
                        <div class="col-md-6">
                            <input id="facebook" type="text" class="form-control @error('facebook') is-invalid @enderror" name="facebook" required>
                            @error('facebook')
                            <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                            @enderror
                        </div>
                    </div>

                    <div class="form-group row">
                        <label for="linked_in" class="col-md-4 col-form-label text-md-right">LinkedIn</label>
                        <div class="col-md-6">
                            <input id="linked_in" type="text" class="form-control @error('linked_in') is-invalid @enderror" name="linked_in" required>
                            @error('linked_in')
                            <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                            @enderror
                        </div>
                    </div>

                    <div class="form-group row">
                        <label for="twitter" class="col-md-4 col-form-label text-md-right">Twitter</label>
                        <div class="col-md-6">
                            <input id="twitter" type="text" class="form-control @error('twitter') is-invalid @enderror" name="twitter" required>
                            @error('twitter')
                            <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                            @enderror
                        </div>
                    </div>
                    <div class="form-group row">
                        <label for="instagram" class="col-md-4 col-form-label text-md-right">Instagram</label>
                        <div class="col-md-6">
                            <input id="instagram" type="text" class="form-control @error('instagram') is-invalid @enderror" name="instagram" required>
                            @error('instagram')
                            <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                            @enderror
                        </div>
                    </div>

                    <div class="form-group row">
                        <label for="phone" class="col-md-4 col-form-label text-md-right">Phone</label>
                        <div class="col-md-6">
                            <input id="phone" type="text" class="form-control @error('phone') is-invalid @enderror" name="phone" required>
                            @error('phone')
                            <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                            @enderror
                        </div>
                    </div>

                    <div class="form-group row">
                        <label for="description" class="col-md-4 col-form-label text-md-right">Description</label>
                        <div class="col-md-6">
                            <textarea id="description" type="text" class="form-control" name="description" required></textarea>
                            @error('description')
                            <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                            @enderror
                        </div>
                    </div>


                    <div class="form-group row">

                        <div class="col-md-6">
                            <button type="submit" class="btn btn-info">Submit</button>
                        </div>
                    </div>

                </form>
            </div>
        </div>
    </div>
@endsection


@section('scripts')
<script>
    CKEDITOR.replace( 'description' );
</script>
@endsection

resources/views/settings/edit.blade.php
@extends('layouts.app')


@section('content')
    <div class="container">
        <div class="row">

            @if(Session::has('flash_message'))
                <div class="alert alert-success">
                    {{ Session::get('flash_message') }}
                </div>
            @endif

            <div class="col-12">
                <form action="{{ route('settings.update', $settings) }}" method="POST" enctype="multipart/form-data">
                    @method('PUT')
                    @csrf


                    <div class="form-group row">
                        <label for="image" class="col-md-4 col-form-label text-md-right">Upload Logo</label>
                        <div class="col-md-6">
                            <input id="image" type="file" class="form-control @error('image') is-invalid @enderror" name="image" >
                            @error('url')
                            <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                            @enderror
                        </div>
                    </div>

                    <div class="form-group row">
                        <label for="url" class="col-md-4 col-form-label text-md-right">URL</label>
                        <div class="col-md-6">
                            <input id="url" type="text" class="form-control @error('url') is-invalid @enderror" value="{{ $settings->url}}" name="url" autocomplete="url" required autofocus>
                            @error('url')
                            <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                            @enderror

                        </div>
                    </div>



                    <div class="form-group row">
                        <label for="title" class="col-md-4 col-form-label text-md-right">Title</label>
                        <div class="col-md-6">
                            <input id="title" type="text" class="form-control @error('title') is-invalid @enderror" value="{{ $settings->title }}" name="title" required >
                            @error('title')
                            <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                            @enderror
                        </div>
                    </div>

                    <div class="form-group row">
                        <label for="name" class="col-md-4 col-form-label text-md-right">Email</label>
                        <div class="col-md-6">
                            <input id="name" type="email" class="form-control @error('email') is-invalid @enderror" name="email" value="{{ $settings->email }}"  required>
                            @error('email')
                            <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                            @enderror
                        </div>
                    </div>


                    <div class="form-group row">
                        <label for="facebook" class="col-md-4 col-form-label text-md-right">Facebook</label>
                        <div class="col-md-6">
                            <input id="facebook" type="text" class="form-control @error('facebook') is-invalid @enderror" value="{{ $settings->facebook }}" name="facebook" required>
                            @error('facebook')
                            <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                            @enderror
                        </div>
                    </div>

                    <div class="form-group row">
                        <label for="linkedin" class="col-md-4 col-form-label text-md-right">LinkedIn</label>
                        <div class="col-md-6">
                            <input id="linkedin" type="text" class="form-control @error('linkedin') is-invalid @enderror" value="{{ $settings->linkedin }}" name="linkedin" required>
                            @error('linkedin')
                            <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                            @enderror
                        </div>
                    </div>

                    <div class="form-group row">
                        <label for="twitter" class="col-md-4 col-form-label text-md-right">Twitter</label>
                        <div class="col-md-6">
                            <input id="twitter" type="text" class="form-control @error('twitter') is-invalid @enderror" value="{{ $settings->twitter }}" name="twitter" required>
                            @error('twitter')
                            <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                            @enderror
                        </div>
                    </div>
                    <div class="form-group row">
                        <label for="instagram" class="col-md-4 col-form-label text-md-right">Twitter</label>
                        <div class="col-md-6">
                            <input id="instagram" type="text" class="form-control @error('instagram') is-invalid @enderror" value="{{ $settings->instagram }}" name="instagram" required>
                            @error('instagram')
                            <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                            @enderror
                        </div>
                    </div>

                    <div class="form-group row">
                        <label for="phone" class="col-md-4 col-form-label text-md-right">Phone</label>
                        <div class="col-md-6">
                            <input id="phone" type="text" class="form-control @error('phone') is-invalid @enderror" value="{{ $settings->phone }}" name="phone" required>
                            @error('phone')
                            <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                            @enderror
                        </div>
                    </div>

                    <div class="form-group row">
                        <label for="description" class="col-md-4 col-form-label text-md-right">Description</label>
                        <div class="col-md-6">
                            <textarea id="description" type="text" class="form-control" name="description" required>{{ $settings->description }}</textarea>
                            @error('description')
                            <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                            @enderror
                        </div>
                    </div>


                    <div class="form-group row">

                        <div class="col-md-6">
                            <button type="submit" class="btn btn-info">Submit</button>
                        </div>
                    </div>

                </form>
            </div>
        </div>
    </div>
@endsection


@section('scripts')
    <script>
        CKEDITOR.replace( 'description' );
    </script>
@endsection